//
//  CreateSkillOtherModels.swift
//  miniTopgun
//
//  Created by itthipon wiwatthanasathit on 7/30/2560 BE.
//  Copyright (c) 2560 Izpal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CreateSkillOther
{
    // MARK: Use cases
    struct BodyRequest {
        var idJsk:String
        var idResume:String
        var idSkill:String
        var nameSkill:String
        var levelSkill:String
    }
    enum Create
    {
        struct Request
        {
            var bodyRequest:BodyRequest
        }
        struct Response
        {
            var SkillOtherList:[SkillOtherData]?
        }
        struct ViewModel
        {
            var SkillOtherList:[SkillOtherData]?
        }
    }
    
    enum Edit
    {
        struct Request
        {
        }
        struct Response
        {
            var SkillOtherList:SkillOtherData
        }
        struct ViewModel
        {
            var SkillOtherList:SkillOtherData
        }
    }
    
    enum Update
    {
        struct Request
        {
            var bodyRequest:BodyRequest
        }
        struct Response
        {
            var SkillOtherList:[SkillOtherData]?
        }
        struct ViewModel
        {
            var SkillOtherList:[SkillOtherData]?
        }
    }
    
    enum MDLevelSkill
    {
        struct Request
        {
        }
        struct Response
        {
            var LevelSkillList:[LevelSkillData]?
        }
        struct ViewModel
        {
            var LevelSkillList:[LevelSkillData]?
        }
    }
}
