//
//  CreateSkillOtherPresenter.swift
//  miniTopgun
//
//  Created by itthipon wiwatthanasathit on 7/30/2560 BE.
//  Copyright (c) 2560 Izpal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CreateSkillOtherPresentationLogic
{
    func presentCreateSkillOther(response: CreateSkillOther.Create.Response)
    func presentUpdateSkillOther(response: CreateSkillOther.Update.Response)
    func presentLevelSkill(response: CreateSkillOther.MDLevelSkill.Response)
    func presentSkillOtherToEdit(response: CreateSkillOther.Edit.Response)
}

class CreateSkillOtherPresenter: CreateSkillOtherPresentationLogic
{
    weak var viewController: CreateSkillOtherDisplayLogic?
    
    // MARK: Do something
    
    func presentCreateSkillOther(response: CreateSkillOther.Create.Response)
    {
        let viewModel = CreateSkillOther.Create.ViewModel(SkillOtherList: response.SkillOtherList)
        viewController?.displayCreateSkillOther(viewModel: viewModel)
    }
    
    func presentUpdateSkillOther(response: CreateSkillOther.Update.Response)
    {
        let viewModel = CreateSkillOther.Update.ViewModel(SkillOtherList: response.SkillOtherList)
        viewController?.displayUpdateSkillOther(viewModel: viewModel)
    }
    
    func presentLevelSkill(response: CreateSkillOther.MDLevelSkill.Response){
        let list = response.LevelSkillList?.filter{$0.iDLEVEL != "0"}
        let viewModel = CreateSkillOther.MDLevelSkill.ViewModel(LevelSkillList: list)
        viewController?.displayLevelSkill(viewModel: viewModel)
    }
    
    func presentSkillOtherToEdit(response: CreateSkillOther.Edit.Response){
        let skilOtherDictEdit = response.SkillOtherList
        let viewModel = CreateSkillOther.Edit.ViewModel(SkillOtherList: skilOtherDictEdit)
        viewController?.displaySkillOtherToEdit(viewModel: viewModel)
    }
    
}
