//
//  CreateSkillOtherRouter.swift
//  miniTopgun
//
//  Created by itthipon wiwatthanasathit on 7/30/2560 BE.
//  Copyright (c) 2560 Izpal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CreateSkillOtherRoutingLogic
{
    func routeToListSkillOther()
}

protocol CreateSkillOtherDataPassing
{
    var dataStore: CreateSkillOtherDataStore? { get }
}

class CreateSkillOtherRouter: NSObject, CreateSkillOtherRoutingLogic, CreateSkillOtherDataPassing
{
    weak var viewController: CreateSkillOtherViewController?
    var dataStore: CreateSkillOtherDataStore?
    
    // MARK: Routing
    
    func routeToListSkillOther()
    {
        _ = viewController!.navigationController!.viewControllers.count - 2
        let destinationVC = viewController?.navigationController?.viewControllers[0] as! SkillOtherViewController
        navigateToListSkillOther(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Navigation
    
    func navigateToListSkillOther(source: CreateSkillOtherViewController, destination: SkillOtherViewController)
    {
        source.navigationController?.popViewController(animated: true)
    }
    
    // MARK: Passing data
    
    
}
