//
//  ShowSkillOtherRouter.swift
//  miniTopgun
//
//  Created by itthipon wiwatthanasathit on 7/24/2560 BE.
//  Copyright (c) 2560 Izpal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ShowSkillOtherRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ShowSkillOtherDataPassing
{
  var dataStore: ShowSkillOtherDataStore? { get }
}

class ShowSkillOtherRouter: NSObject, ShowSkillOtherRoutingLogic, ShowSkillOtherDataPassing
{
  weak var viewController: ShowSkillOtherViewController?
  var dataStore: ShowSkillOtherDataStore?
  
  // MARK: Routing
  
    func routeToUpdateSkillOther(segue: UIStoryboardSegue)
    {
        let destinationVC = segue.destination as! CreateSkillOtherViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToShowOrder(source: dataStore!, destination: &destinationDS)
        print("routeToUpdateSkillOther")
    }

  // MARK: Navigation
  
  //func navigateToSomewhere(source: ShowSkillOtherViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
    
    func passDataToShowOrder(source: ShowSkillOtherDataStore, destination: inout CreateSkillOtherDataStore)
    {
        destination.skillOtherEditDict = source.skillOtherDataEdit 
    }
}
