//
//  SkillOtherPresenter.swift
//  miniTopgun
//
//  Created by Codemobiles on 7/24/2560 BE.
//  Copyright (c) 2560 Izpal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SkillOtherPresentationLogic
{
  func presentSomething(response: SkillOther.FetchAllSkillOther.Response)
}

class SkillOtherPresenter: SkillOtherPresentationLogic
{
  weak var viewController: SkillOtherDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SkillOther.FetchAllSkillOther.Response)
  {
    let viewModel = SkillOther.FetchAllSkillOther.ViewModel(skillOtherList: response.skillOtherList)
    viewController?.displaySomething(viewModel: viewModel)
  }
}
