//
//  SkillOtherRouter.swift
//  miniTopgun
//
//  Created by Codemobiles on 7/24/2560 BE.
//  Copyright (c) 2560 Izpal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SkillOtherRoutingLogic
{
  func routeToShowSkillOther(segue: UIStoryboardSegue)
}

protocol SkillOtherDataPassing
{
  var dataStore: SkillOtherDataStore? { get }
}

class SkillOtherRouter: NSObject, SkillOtherRoutingLogic, SkillOtherDataPassing
{
  weak var viewController: SkillOtherViewController?
  var dataStore: SkillOtherDataStore?
  
  // MARK: Routing
  
    func routeToShowSkillOther(segue: UIStoryboardSegue)
    {
        let destinationVC = segue.destination as! ShowSkillOtherViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToShowOrder(source: dataStore!, destination: &destinationDS) 
        print("routeToShowSkillOther")
    }
    
    func routeToCreateSkillOther(segue: UIStoryboardSegue)
    {
        print("routeToCreateSkillOther")
    }
  // MARK: Navigation
  
    func navigateToShowOrder(source: SkillOtherViewController, destination: ShowSkillOtherViewController)
    {
        source.show(destination, sender: nil)
    }
    
   
  // MARK: Passing data
  
    func passDataToShowOrder(source: SkillOtherDataStore, destination: inout ShowSkillOtherDataStore)
    {
        let selectedRow = viewController?.mTableView.indexPathForSelectedRow?.row
        destination.skillOtherDataEdit = source.skillOtherList?[selectedRow!]
    }
}
