//
//  SkillOtherModels.swift
//  miniTopgun
//
//  Created by Codemobiles on 7/24/2560 BE.
//  Copyright (c) 2560 Izpal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SkillOther
{
    struct skillOtherField {
        var idJsk:String
        var idResume:String	
    }
    
    // MARK: Use cases
     
    enum FetchAllSkillOther
    {
        struct Request
        {
            var skillOtherField:skillOtherField
        }
        struct Response
        {
            var skillOtherList: [SkillOtherData]?
        }
        struct ViewModel
        {
           var skillOtherList: [SkillOtherData]?
        }
    }
    
}
