//
//  SkillOtherInteractor.swift
//  miniTopgun
//
//  Created by Codemobiles on 7/24/2560 BE.
//  Copyright (c) 2560 Izpal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SkillOtherBusinessLogic
{
  func doSomething(request: SkillOther.Something.Request)
}

protocol SkillOtherDataStore
{
  //var name: String { get set }
}

class SkillOtherInteractor: SkillOtherBusinessLogic, SkillOtherDataStore
{
  var presenter: SkillOtherPresentationLogic?
  var worker: SkillOtherWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SkillOther.Something.Request)
  {
    worker = SkillOtherWorker()
    worker?.doSomeWork()
    
    let response = SkillOther.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
